language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - composer selfupdate
    - composer install --dev --no-interaction
    - COMPOSER_ROOT_VERSION=dev-master composer dump-autoload

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - php vendor/bin/coveralls
